RentAndSell.Car.WebApp/Models/ArabaViewModel.cs
using RentAndSell.Car.WebApp.Commons.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RentAndSell.Car.WebApp.Models
{
	public class ArabaViewModel
	{
        public int Id { get; set; }
        public string Marka { get; set; }
		public string Model { get; set; }
		public MotorTipi MotorTipi { get; set; }
		public YakitTuru YakitTuru { get; set; }
		public SanzimanTipi SanzimanTipi { get; set; }

		[Range(1940,2024)]
		public short Yili { get; set; }
	}
}

RentAndSell.Car.WebApp/Models/ErrorViewModel.cs
namespace RentAndSell.Car.WebApp.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

RentAndSell.Car.WebApp/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RentAndSell.Car.WebApp.Models
{
	public class LoginViewModel
	{
		[Display(Name = "Kullanıcı Adı")]
		public string UserName { get; set; }

        [Display(Name ="Şifre")]
		[DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

RentAndSell.Car.WebApp/Models/TokenResultViewModel.cs
namespace RentAndSell.Car.WebApp.Models
{
	public class TokenResultViewModel
	{
        public string Token { get; set; }
    }
}

RentAndSell.Car.WebApp/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using RentAndSell.Car.WebApp.Models;
using System.Security.Claims;

namespace RentAndSell.Car.WebApp.Controllers
{
	public class AccountController : Controller
	{
		private readonly HttpClient _httpClient;
		private const string _endPoint = "Auth";

		public AccountController(HttpClient httpClient)
		{
			_httpClient = httpClient;
			_httpClient.BaseAddress = new Uri("https://localhost:7247/api/");
		}

		[HttpGet]
		public IActionResult Login()
		{
			LoginViewModel model = new LoginViewModel();

			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> Login(LoginViewModel model)
		{
			if (!ModelState.IsValid)
				return View(model);

			//Burada api ye Auth/LoginWithJwt ye istek atacağız token değerimizi alacağız
			HttpResponseMessage responseMessage = _httpClient.PostAsJsonAsync<LoginViewModel>(_endPoint + "/LoginWithJwt", model).Result;

			if (responseMessage.IsSuccessStatusCode)
			{
				TokenResultViewModel result = responseMessage.Content.ReadFromJsonAsync<TokenResultViewModel>().Result;

				if (!string.IsNullOrEmpty(result.Token))
				{
					List<Claim> claims = new List<Claim>
					{
					new Claim(ClaimTypes.Name,model.UserName),
					new Claim(ClaimTypes.NameIdentifier,"1")
					};

					ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

					ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

					await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,claimsPrincipal);

					HttpContext.Session.SetString("Token",result.Token);

					return RedirectToAction("Index","Home");
				}

				
			}

			return View(model);
		}

		[HttpGet]
		public IActionResult Logout()
		{
			HttpContext.Session.Clear();
			HttpContext.SignOutAsync();

			return RedirectToAction("Index","Home");
		}
	}
}

RentAndSell.Car.WebApp/Controllers/ArabaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RentAndSell.Car.WebApp.Models;
using System.Net.Http.Headers;

namespace RentAndSell.Car.WebApp.Controllers
{
	[Authorize]
	public class ArabaController : Controller
	{
		private readonly HttpClient _httpClient;
		private readonly IHttpContextAccessor _httpContextAccessor;	
		private const string _endPoint = "Cars";
		private readonly string _token;

		public ArabaController(HttpClient httpClient, IHttpContextAccessor httpContextAccessor)
		{
			_httpClient = httpClient;
			_httpContextAccessor = httpContextAccessor;

            _token = _httpContextAccessor.HttpContext.Session.GetString("Token");

			_httpClient.BaseAddress = new Uri("https://localhost:7247/api/");
			_httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _token);
		}

		// GET: ArabaController
		public ActionResult Index()
		{
			List<ArabaViewModel> model = _httpClient.GetFromJsonAsync<List<ArabaViewModel>>(_endPoint).Result;

			
			return View(model);
		}

		// GET: ArabaController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: ArabaController/Create
		public ActionResult Create()
		{
			ArabaViewModel model = new ArabaViewModel();

			ViewBag.Token = _token;

			return View(model);
		}

		// POST: ArabaController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ArabaController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: ArabaController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ArabaController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: ArabaController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

RentAndSell.Car.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RentAndSell.Car.WebApp.Models;
using System.Diagnostics;

namespace RentAndSell.Car.WebApp.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

RentAndSell.Car.WebApp/Views/Araba/Create.cshtml
@using RentAndSell.Car.WebApp.Commons.Enums
@model ArabaViewModel
@{

    List<SelectListItem> yillar = new List<SelectListItem>();

    for (int i = 1940; i <= DateTime.Now.Year; i++)
    {
        yillar.Add(new SelectListItem(i.ToString(), i.ToString()));
    }


}
<form id="createCar">
    <div class="row g-3">
        <div class="col-md-12">
            <input asp-for="Marka" class="form-control" placeholder="@Html.DisplayNameFor(m => m.Marka)" />
            <span asp-validation-for="Marka" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <input asp-for="Model" class="form-control" placeholder="@Html.DisplayNameFor(m => m.Model)" />
            <span asp-validation-for="Model" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <select asp-for="Yili" class="form-control" asp-items="@yillar"></select>
            <span asp-validation-for="Yili" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <select asp-for="YakitTuru" class="form-select" asp-items="Html.GetEnumSelectList<YakitTuru>()"></select>
            <span asp-validation-for="YakitTuru" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <select asp-for="SanzimanTipi" class="form-select" asp-items="Html.GetEnumSelectList<SanzimanTipi>()"></select>
            <span asp-validation-for="SanzimanTipi" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <select asp-for="MotorTipi" class="form-select" asp-items="Html.GetEnumSelectList<MotorTipi>()"></select>
            <span asp-validation-for="MotorTipi" class="text-danger"></span>
        </div>
        <div class="col-md-12">
            <input type="button" class="btn btn-primary" value="Gönder" onclick="CreateCar();" />
        </div>
    </div>

</form>

<input type="hidden" id="_token" value="@ViewBag.Token" />

@section Scripts
{
    <script type="text/javascript" src="~/js/araba/create.js"></script>
}

RentAndSell.Car.WebApp/Views/Araba/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>Delete Sayfası</p>

RentAndSell.Car.WebApp/Views/Araba/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>Detay Sayfası</p>

RentAndSell.Car.WebApp/Views/Araba/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>Edit Sayfası</p>

RentAndSell.Car.WebApp/Views/Araba/Index.cshtml
@model List<ArabaViewModel>

<p>Index Sayfası</p>

        <table class="table">
        <thead>
        <tr>
        <th>Id</th>
        <th>Marka</th>
        <th>Model</th>
        <th>Yılı</th>
        <th>Motor Tipi</th>
        <th>Şanzıman Tipi</th>
        <th>Yakıt Türü</th>
        </tr>
        </thead>
        <tbody>
        @if (Model.Any())
        {
            foreach (ArabaViewModel araba in Model)
            {
                <tr>
                <th>@araba.Id</th>
                <th>@araba.Marka</th>
                <th>@araba.Model</th>
                <th>@araba.Yili</th>
                <th>@araba.MotorTipi</th>
                <th>@araba.SanzimanTipi</th>
                <th>@araba.YakitTuru</th>
                </tr>
            }
        }
        else
        {
            <tr class="text-center text-muted">
            <td colspan="7">
            <p>Kayıt Yok</p>
            </td>
            </tr>
        }
        </tbody>
        <tr>
        <th>Id</th>
        <th>Marka</th>
        <th>Model</th>
        <th>Yılı</th>
        <th>Motor Tipi</th>
        <th>Şanzıman Tipi</th>
        <th>Yakıt Türü</th>
        </tr>
        </table>

RentAndSell.Car.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RentAndSell.Car.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentAndSell.Car.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentAndSell.Car.WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentAndSell.Car.WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(Context.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Araba" asp-action="Index">Arabalar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Çıkış</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Giriş</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RentAndSell.Car.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>